### ISSUE TITLE
请问tinper的grid表格合计行自动计算的数值小数点后位数很长很长怎么办？现需要做保留两位处理

### ISSUE THREAD

**Issue by tt1262360978** [iuap-design/moy#9]
### Bug 报告

- __Package version(s)__: 3.2.4

#### 描述这个问题:

请问tinper官网支持grid表格合计行自动计算的数值小数点很长很长怎么办？

#### 期望的行为:

需要做保留两位处理，请问tinper官网支持grid表格合计行自定义计算方法吗？

**Comment by GuoYongfeng** [comment]
@tt1262360978 这个框架目前已暂停维护，如果问题请向上反馈或发邮件。

**Comment by tt1262360978** [comment]
> @tt1262360978 这个框架目前已暂停维护，如果问题请向上反馈或发邮件。

好的，已改源码解决￣□￣｜｜
